ln -sv ~/source/dotfiles/.bash_profile ~/.bash_profile
ln -sv ~/source/dotfiles/.bash_profile ~/.zshrc
ln -sv ~/source/dotfiles/.config ~/.config
ln -sv ~/source/dotfiles/.gitconfig ~/.gitconfig
ln -sv ~/source/dotfiles/.skhdrc ~/.skhdrc
ln -sv ~/source/dotfiles/.tmux.conf ~/.tmux.conf
ln -sv ~/source/dotfiles/.tmux.theme.conf ~/.tmux.theme.conf
ln -sv ~/source/dotfiles/.tmux.theme.dark.conf ~/.tmux.theme.dark.conf
ln -sv ~/source/dotfiles/.tmux.theme.light.conf ~/.tmux.theme.light.conf
ln -sv ~/source/dotfiles/.vimrc ~/.vimrc
ln -sv ~/source/dotfiles/.yabai ~/.yabairc
ln -sv ~/source/dotfiles/dark-theme.sh ~/dark-theme.sh
ln -sv ~/source/dotfiles/light-theme.sh ~/light-theme.sh
ln -sv ~/source/dotfiles/kitty ~/kitty
ln -sv ~/source/dotfiles/dev-tmux ~/dev-tmux
